library(shinydashboard)
library(shinythemes)
library(tidyverse)
library(ggplot2)
library(magrittr)
# for word clouds
library(tm)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)

# load datsets
medicaid <- readRDS('data/MedicaidExpansion.RDS')
populations <- readRDS('data/StatePopulations.RDS')
ERVisitsPer1k <- readRDS('data/ERVisitsPer1k.RDS')
insurance2008 <- readRDS('data/InsuranceCoverageTotal2008.RDS')
insurance2009 <- readRDS('data/InsuranceCoverageTotal2009.RDS')
insurance2010 <- readRDS('data/InsuranceCoverageTotal2010.RDS')
insurance2011 <- readRDS('data/InsuranceCoverageTotal2011.RDS')
insurance2012 <- readRDS('data/InsuranceCoverageTotal2012.RDS')
insurance2013 <- readRDS('data/InsuranceCoverageTotal2013.RDS')
insurance2014 <- readRDS('data/InsuranceCoverageTotal2014.RDS')
insurance2015 <- readRDS('data/InsuranceCoverageTotal2015.RDS')
insurance2016 <- readRDS('data/InsuranceCoverageTotal2016.RDS')
insurance2017 <- readRDS('data/InsuranceCoverageTotal2017.RDS')

